import { existsSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import type { PostStepResult } from '@hexp/shared'

interface GenerateDocsOptions {
  skipDocs?: boolean
  template?: string
}

function generateReadmeContent(
  projectName: string,
  context: Record<string, unknown>
): string {
  const projectType = context.projectType || 'single'
  const isMonorepo = projectType === 'monorepo'

  return `# ${projectName}

${isMonorepo ? 'A monorepo project' : 'A project'} generated with Hexperience Platform.

## Getting Started

### Prerequisites

- Node.js >= 18.12.0
- ${isMonorepo ? 'pnpm >= 9.0.0' : 'pnpm, npm, or yarn'}

### Installation

\`\`\`bash
${isMonorepo ? 'pnpm install' : 'npm install'}
\`\`\`

### Development

\`\`\`bash
${isMonorepo ? 'pnpm dev' : 'npm run dev'}
\`\`\`

## Project Structure

${
  isMonorepo
    ? `\`\`\`
${projectName}/
├── apps/          # Applications
├── packages/      # Shared packages
├── turbo.json     # Turbo configuration
└── pnpm-workspace.yaml
\`\`\``
    : 'See individual package directories for structure.'
}

## Available Scripts

${isMonorepo ? 'Run scripts from the root:' : 'Run from the project root:'}

- \`${isMonorepo ? 'pnpm' : 'npm'} run build\` - Build the project
- \`${isMonorepo ? 'pnpm' : 'npm'} run dev\` - Start development mode
- \`${isMonorepo ? 'pnpm' : 'npm'} run lint\` - Run linter
- \`${isMonorepo ? 'pnpm' : 'npm'} run format\` - Format code
- \`${isMonorepo ? 'pnpm' : 'npm'} run type-check\` - Type check
- \`${isMonorepo ? 'pnpm' : 'npm'} run test\` - Run tests

## Next Steps

1. Review the generated project structure
2. Customize configuration files as needed
3. Start developing your application
4. Add your first feature

## Documentation

For more information, see the project documentation or visit the Hexperience Platform documentation.

---

Generated by [Hexperience Platform](https://github.com/hexperience/platform)
`
}

export async function executeGenerateDocs(
  workspaceRoot: string,
  context: Record<string, unknown>,
  options: GenerateDocsOptions
): Promise<PostStepResult> {
  try {
    if (options.skipDocs) {
      return {
        success: true,
        message: 'Documentation generation skipped',
      }
    }

    const projectName = (context.projectName as string) || 'Project'
    const readmePath = resolve(workspaceRoot, 'README.md')

    // Check if README already exists
    if (existsSync(readmePath) && !options.template) {
      return {
        success: true,
        message: 'README.md already exists, skipping generation',
      }
    }

    // Generate README content
    const content = options.template
      ? options.template.replace(/\{\{projectName\}\}/g, projectName)
      : generateReadmeContent(projectName, context)

    // Write README
    writeFileSync(readmePath, content, 'utf-8')

    return {
      success: true,
      message: 'README.md generated successfully',
    }
  } catch (error) {
    return {
      success: false,
      error: `Failed to generate documentation: ${error instanceof Error ? error.message : String(error)}`,
    }
  }
}
