pre-commit:
  parallel: true
  commands:
    biome:
      run: pnpm biome check --write --no-errors-on-unmatched --files-ignore-unknown=true {staged_files}
      stage_fixed: true
      glob: "*.{js,jsx,ts,tsx,json,jsonc}"

commit-msg:
  commands:
    commitlint:
      run: pnpm commitlint --edit {1}

pre-push:
  commands:
    type-check:
      run: pnpm type-check
      glob: "*.{ts,tsx}"

